version: "3"
services: 
  bot:
    build: 
      context: .
      dockerfile: ./docker/bot.dockerfile
    container_name: scrumbot_bot

  server:
    build: 
      context: .
      dockerfile: ./docker/server.dockerfile
    container_name: scrumbot_server
    ports:
      - 6543:8000

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ScrumBot
    ports:
      - 26543:27017
  
  frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend.dockerfile
    container_name: scrumbot_frontend
    ports:
      - 6544:5000

